/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    war
     `eclipse-wtp`
}
eclipse {
    wtp {
        component {
            sourceDirs = setOf(
                file("build/classes/java/main"),
                file("build/resources/main")
            )
        }
    }
}
repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
        implementation("org.mybatis:mybatis:3.5.19")
    runtimeOnly("com.mysql:mysql-connector-j:8.0.33")
 
    implementation("org.springframework.security:spring-security-crypto:6.5.2")
implementation("org.mindrot:jbcrypt:0.4")
implementation("org.springframework:spring-context:5.3.39")
implementation("org.springframework:spring-web:5.3.39")
implementation("org.springframework:spring-webmvc:5.3.39")
compileOnly("javax.servlet:javax.servlet-api:4.0.1")
implementation("javax.servlet:jstl:1.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
